spring.application.name=proveedor
 
spring.datasource.url=jdbc:oracle:thin:@df1_high?TNS_ADMIN=./Wallet_DF1
spring.datasource.username=NutriPetBD
spring.datasource.password=7_9tmvh78EMmR
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

#Editar el port (Colocar el numero indicado del ms)
server.port=8088